// This file contains test data for the products module.
package models

var ProductToAdd = Product{
	Name:               "Produto Teste",
	DetailedName:       "Produto Teste Detalhado",
	Description:        "Teste de criação de produto",
	Status:             "ativo",
	SKU:                "TESTE123",
	Barcode:            "1234567890123",
	ExternalID:         "EXT123",
	Coin:               "BRL",
	Price:              123.45,
	SalesPrice:         110.00,
	CostPrice:          100.00,
	Stock:              10,
	Type:               "Produto",
	ProductGroup:       "Grupo Teste",
	ProductCategory:    "Categoria Teste",
	ProductSubcategory: "Subcategoria Teste",
	Tags:               []string{"tag1", "tag2"},
	Manufacturer:       "Fabricante Teste",
	ManufacturerCode:   "FAB123",
	NCM:                "12345678",
	CEST:               "123456",
	CNAE:               "1234567",
	Origin:             string(OriginNacionalExceto3_4_5_8),
	Images:             []string{"image1.jpg", "image2.jpg"},
	Documents:          []string{"doc1.pdf", "doc2.pdf"},
}

var ProductToUpdate = Product{
	Name:               "Produto Atualizado",
	DetailedName:       "Produto Atualizado Detalhado",
	Description:        "Produto atualizado com novos detalhes",
	Status:             "desativado",
	SKU:                "ATUALIZADO123",
	Barcode:            "9876543210987",
	ExternalID:         "EXT456",
	Coin:               "USD",
	Price:              200.00,
	SalesPrice:         180.00,
	CostPrice:          150.00,
	Stock:              20,
	Type:               "Serviço",
	ProductGroup:       "Grupo Atualizado",
	ProductCategory:    "Categoria Atualizada",
	ProductSubcategory: "Subcategoria Atualizada",
	Tags:               []string{"tag3", "tag4"},
	Manufacturer:       "Fabricante Atualizado",
	ManufacturerCode:   "FAB456",
	NCM:                "87654321",
	CEST:               "654321",
	CNAE:               "7654321",
	Origin:             string(OriginEstrangeiraImportacaoDireta),
	Images:             []string{"updated_image1.jpg", "updated_image2.jpg"},
	Documents:          []string{"updated_doc1.pdf", "updated_doc2.pdf"},
}
